-- AlterTable
ALTER TABLE `leads` ADD COLUMN `postponeReason` VARCHAR(32) NULL,
    MODIFY `stage` ENUM('SYGNAL', 'WYWIAD', 'OFERTA', 'REZERWACJA', 'WYGRANA', 'PRZEGRANA', 'ODLOZONE') NOT NULL DEFAULT 'SYGNAL';

